Add support for import.meta.hot
OpenSourceRaidGuild/babel-vite pull request #15
Opened 2023-01-15 03:04 UTC by 0kzh

Closes https://github.com/OpenSourceRaidGuild/babel-vite/issues/3

**What/Why**:
Some modules use `import.meta.hot` to implement hot module reloading support. However, when running these test in Jest, this causes an error.

**How**:
Created a new plugin that looks for `import.meta.hot` and replaces it with `module.hot`

**Checklist**:
- [x] Documentation updated
- [x] Tests
- [x] Ready to be merged
- [ ] Added myself to contributors table

2023-01-15 21:03 UTC, mpeyper requested changes
Good job with this!

Functionally I’m happy with it, just some documentation needs updating.

2023-01-15 21:03 UTC, mpeyper commented on packages/babel-plugin-transform-vite-meta-hot/README.md
> +# babel-plugin-transform-vite-meta-env
This README needs to be updated to document `hot` instead of `env`

2023-01-15 21:03 UTC, mpeyper commented on packages/babel-plugin-transform-vite-meta-hot/package.json
> +    "env"
Should have `hot` keyword instead. `hot` should be added to the preset’s `package.json` keywords too.

2023-01-15 23:09 UTC, 0kzh commented
Thanks! And good catch, missed those on my first pass. Should be updated now.

2023-01-20 20:21 UTC, 0kzh commented
Hey @mpeyper, bumping this whenever you're free to merge!

Thanks again for your work on this library :)

2023-01-22 09:22 UTC, mpeyper approved these changes

2023-01-22 09:24 UTC, merged